language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
branches:
  only:
    master
cache:
  directories:
    - $HOME/.cache
before_install:
  - pip install --upgrade pip
install:
  - pip install --upgrade -r travis-ci-requirements.txt
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core sdafile --exe
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
